with open("app/api/routes.py", "a", encoding="utf-8") as f:
    f.write("\n")
    f.write("@router.get(\"/api/judge/assignments\", response_model=List[AssignmentResponse])\n")
    f.write("async def get_judge_assignments(\n")
    f.write("    event_id: int,\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    authz.require_judge(event_id)\n")
    f.write("    assignments = db.execute(\n")
    f.write("        select(JudgeAssignment).where(\n")
    f.write("            JudgeAssignment.event_id == event_id,\n")
    f.write("            JudgeAssignment.judge_id == current_user.id\n")
    f.write("        )\n")
    f.write("    ).scalars().all()\n")
    f.write("    result = []\n")
    f.write("    for assignment in assignments:\n")
    f.write("        project = db.get(Project, assignment.project_id)\n")
    f.write("        review = db.execute(\n")
    f.write("            select(Review).where(Review.assignment_id == assignment.id)\n")
    f.write("        ).scalar_one_or_none()\n")
    f.write("        review_resp = None\n")
    f.write("    if review:\n")
    f.write("        scores = db.execute(\n")
    f.write("            select(Score).where(Score.review_id == review.id)\n")
    f.write("        ).scalars().all()\n")
    f.write("        score_responses = []\n")
    f.write("        for score in scores:\n")
    f.write("            criterion = db.get(Criterion, score.criterion_id)\n")
    f.write("            score_responses.append(ScoreResponse(\n")
    f.write("                id=score.id,\n")
    f.write("                criterion_id=score.criterion_id,\n")
    f.write("                criterion_label=criterion.label if criterion else \"\",\n")
    f.write("                weight=float(criterion.weight) if criterion else 0,\n")
    f.write("                value=float(score.value),\n")
    f.write("                comment=score.comment\n")
    f.write("            ))\n")
    f.write("        review_resp = ReviewResponse(\n")
    f.write("            id=review.id,\n")
    f.write("            assignment_id=review.assignment_id,\n")
    f.write("            judge_id=review.judge_id,\n")
    f.write("            status=review.status,\n")
    f.write("            general_comments=review.general_comments,\n")
    f.write("            submitted_at=review.submitted_at,\n")
    f.write("            scores=score_responses\n")
    f.write("        )\n")
    f.write("    result.append(AssignmentResponse(\n")
    f.write("        id=assignment.id,\n")
    f.write("        event_id=assignment.event_id,\n")
    f.write("        judge_id=assignment.judge_id,\n")
    f.write("        project_id=assignment.project_id,\n")
    f.write("        batch_id=assignment.batch_id,\n")
    f.write("        status=assignment.status,\n")
    f.write("        assigned_at=assignment.assigned_at,\n")
    f.write("        started_at=assignment.started_at,\n")
    f.write("        completed_at=assignment.completed_at,\n")
    f.write("        project_title=project.title if project else None,\n")
    f.write("        review=review_resp\n")
    f.write("    ))\n")
    f.write("    return result\n\n")
    f.write("@router.post(\"/api/judge/reviews/{assignment_id}\", response_model=ReviewResponse)\n")
    f.write("async def submit_review(\n")
    f.write("    assignment_id: int,\n")
    f.write("    review_data: ReviewCreate,\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    assignment = db.get(JudgeAssignment, assignment_id)\n")
    f.write("    if not assignment:\n")
    f.write("        raise HTTPException(status_code=404, detail=\"Assignment not found\")\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    authz.require_judge_assignment(assignment.project_id, assignment.event_id)\n")
    f.write("    review = db.execute(\n")
    f.write("        select(Review).where(Review.assignment_id == assignment_id)\n")
    f.write("    ).scalar_one_or_none()\n")
    f.write("    if not review:\n")
    f.write("        review = Review(assignment_id=assignment_id, judge_id=current_user.id)\n")
    f.write("        db.add(review)\n")
    f.write("        db.flush()\n")
    f.write("    review.general_comments = review_data.general_comments\n")
    f.write("    review.status = ReviewStatus.SUBMITTED\n")
    f.write("    review.submitted_at = datetime.now(timezone.utc)\n")
    f.write("    db.execute(\n")
    f.write("        Score.__table__.delete().where(Score.review_id == review.id)\n")
    f.write("    )\n")
    f.write("    for score_input in review_data.scores:\n")
    f.write("        criterion = db.get(Criterion, score_input.criterion_id)\n")
    f.write("        if not criterion:\n")
    f.write("            continue\n")
    f.write("        score = Score(\n")
    f.write("            review_id=review.id,\n")
    f.write("            criterion_id=score_input.criterion_id,\n")
    f.write("            value=score_input.value,\n")
    f.write("            comment=score_input.comment\n")
    f.write("        )\n")
    f.write("        db.add(score)\n")
    f.write("    assignment.status = AssignmentStatus.COMPLETED\n")
    f.write("    assignment.completed_at = datetime.now(timezone.utc)\n")
    f.write("    db.commit()\n")
    f.write("    scores = db.execute(\n")
    f.write("        select(Score).where(Score.review_id == review.id)\n")
    f.write("    ).scalars().all()\n")
    f.write("    score_responses = []\n")
    f.write("    for score in scores:\n")
    f.write("        criterion = db.get(Criterion, score.criterion_id)\n")
    f.write("        score_responses.append(ScoreResponse(\n")
    f.write("            id=score.id,\n")
    f.write("            criterion_id=score.criterion_id,\n")
    f.write("            criterion_label=criterion.label if criterion else \"\",\n")
    f.write("            weight=float(criterion.weight) if criterion else 0,\n")
    f.write("            value=float(score.value),\n")
    f.write("            comment=score.comment\n")
    f.write("        ))\n")
    f.write("    return ReviewResponse(\n")
    f.write("        id=review.id,\n")
    f.write("        assignment_id=review.assignment_id,\n")
    f.write("        judge_id=review.judge_id,\n")
    f.write("        status=review.status,\n")
    f.write("        general_comments=review.general_comments,\n")
    f.write("        submitted_at=review.submitted_at,\n")
    f.write("        scores=score_responses\n")
    f.write("    )\n\n")
    f.write("@router.get(\"/api/organizer/events/{event_id}/progress\", response_model=JudgingProgressResponse)\n")
    f.write("async def get_judging_progress(\n")
    f.write("    event_id: int,\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    authz.require_organizer(event_id)\n")
    f.write("    event = db.get(Event, event_id)\n")
    f.write("    if not event:\n")
    f.write("        raise HTTPException(status_code=404, detail=\"Event not found\")\n")
    f.write("    assignments = db.execute(\n")
    f.write("        select(JudgeAssignment).where(JudgeAssignment.event_id == event_id)\n")
    f.write("    ).scalars().all()\n")
    f.write("    total = len(assignments)\n")
    f.write("    completed = 0\n")
    f.write("    in_progress = 0\n")
    f.write("    unstarted = 0\n")
    f.write("    batch_stats = {}\n")
    f.write("    for assignment in assignments:\n")
    f.write("        review = db.execute(\n")
    f.write("            select(Review).where(Review.assignment_id == assignment.id)\n")
    f.write("        ).scalar_one_or_none()\n")
    f.write("    batch_id = assignment.batch_id or 0\n")
    f.write("    if batch_id not in batch_stats:\n")
    f.write("        batch_stats[batch_id] = {\"total\": 0, \"completed\": 0, \"in_progress\": 0, \"unstarted\": 0}\n")
    f.write("    batch_stats[batch_id][\"total\"] += 1\n")
    f.write("    if review and review.status == ReviewStatus.SUBMITTED:\n")
    f.write("        completed += 1\n")
    f.write("        batch_stats[batch_id][\"completed\"] += 1\n")
    f.write("    elif review and review.status in [ReviewStatus.DRAFT, ReviewStatus.IN_PROGRESS]:\n")
    f.write("        in_progress += 1\n")
    f.write("        batch_stats[batch_id][\"in_progress\"] += 1\n")
    f.write("    else:\n")
    f.write("        unstarted += 1\n")
    f.write("        batch_stats[batch_id][\"unstarted\"] += 1\n")
    f.write("    batches = db.execute(\n")
    f.write("        select(ReviewBatch).where(ReviewBatch.event_id == event_id)\n")
    f.write("    ).scalars().all()\n")
    f.write("    batch_names = {b.id: b.name for b in batches}\n")
    f.write("    batch_names[0] = \"Unbatched\"\n")
    f.write("    batch_progress = []\n")
    f.write("    for batch_id, stats in batch_stats.items():\n")
    f.write("        batch_progress.append(BatchProgressResponse(\n")
    f.write("            batch_id=batch_id,\n")
    f.write("            batch_name=batch_names.get(batch_id, f\"Batch {batch_id}\"),\n")
    f.write("            total_assignments=stats[\"total\"],\n")
    f.write("            completed_assignments=stats[\"completed\"],\n")
    f.write("            in_progress_assignments=stats[\"in_progress\"],\n")
    f.write("            unstarted_assignments=stats[\"unstarted\"],\n")
    f.write("            completion_rate=stats[\"completed\"] / stats[\"total\"] if stats[\"total\"] > 0 else 0\n")
    f.write("        ))\n")
    f.write("    return JudgingProgressResponse(\n")
    f.write("    event_id=event_id,\n")
    f.write("    total_assignments=total,\n")
    f.write("    completed_reviews=completed,\n")
    f.write("    in_progress_reviews=in_progress,\n")
    f.write("    unstarted_reviews=unstarted,\n")
    f.write("    overall_completion_rate=completed / total if total > 0 else 0,\n")
    f.write("    batches=batch_progress\n")
    f.write("    )\n\n")
    f.write("@router.post(\"/api/organizer/events/{event_id}/normalize\", response_model=NormalizationRunResponse)\n")
    f.write("async def run_normalization(\n")
    f.write("    event_id: int,\n")
    f.write("    run_data: NormalizationRunCreate,\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    authz.require_organizer(event_id)\n")
    f.write("    service = NormalizationService(db)\n")
    f.write("    run = service.run_normalization(\n")
    f.write("        event_id=event_id,\n")
    f.write("        rubric_id=run_data.rubric_id,\n")
    f.write("        method=run_data.method,\n")
    f.write("        initiated_by=current_user.id,\n")
    f.write("        parameters=run_data.parameters\n")
    f.write("    )\n")
    f.write("    return NormalizationRunResponse.from_orm(run)\n\n")
    f.write("@router.get(\"/api/organizer/events/{event_id}/results\", response_model=List[RunWithResultsResponse])\n")
    f.write("async def get_results(\n")
    f.write("    event_id: int,\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    authz.require_organizer(event_id)\n")
    f.write("    runs = db.execute(\n")
    f.write("        select(NormalizationRun).where(NormalizationRun.event_id == event_id)\n")
    f.write("        .order_by(NormalizationRun.created_at.desc())\n")
    f.write("    ).scalars().all()\n")
    f.write("    result = []\n")
    f.write("    for run in runs:\n")
    f.write("        run_resp = RunWithResultsResponse.from_orm(run)\n")
    f.write("        results = db.execute(\n")
    f.write("            select(Result).where(Result.run_id == run.id)\n")
    f.write("        ).scalars().all()\n")
    f.write("        run_resp.results = [ResultResponse.from_orm(r) for r in results]\n")
    f.write("        result.append(run_resp)\n")
    f.write("    return result\n\n")
    f.write("@router.post(\"/api/organizer/normalization/{run_id}/publish\")\n")
    f.write("async def publish_results(\n")
    f.write("    run_id: int,\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    run = db.get(NormalizationRun, run_id)\n")
    f.write("    if not run:\n")
    f.write("        raise HTTPException(status_code=404, detail=\"Normalization run not found\")\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    authz.require_organizer(run.event_id)\n")
    f.write("    run.is_published = True\n")
    f.write("    run.published_at = datetime.now(timezone.utc)\n")
    f.write("    db.commit()\n")
    f.write("    return {\"message\": \"Results published\"}\n\n")
    f.write("@router.get(\"/api/export.csv\")\n")
    f.write("async def export_csv(\n")
    f.write("    event_id: int,\n")
    f.write("    type: str = \"summary\",\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    authz.require_organizer(event_id)\n")
    f.write("    service = CSVExportService(db)\n")
    f.write("    if type == \"summary\":\n")
    f.write("        csv_content = service.export_event_summary(event_id)\n")
    f.write("        filename = f\"event_{event_id}_summary.csv\"\n")
    f.write("    elif type == \"judging\":\n")
    f.write("        csv_content = service.export_judging_details(event_id)\n")
    f.write("        filename = f\"event_{event_id}_judging.csv\"\n")
    f.write("    elif type == \"teams\":\n")
    f.write("        csv_content = service.export_teams(event_id)\n")
    f.write("        filename = f\"event_{event_id}_teams.csv\"\n")
    f.write("    else:\n")
    f.write("        raise HTTPException(status_code=400, detail=\"Invalid export type\")\n")
    f.write("    return Response(\n")
    f.write("        content=csv_content,\n")
    f.write("        media_type=\"text/csv\",\n")
    f.write("        headers={\"Content-Disposition\": f\"attachment; filename={filename}\"}\n")
    f.write("    )\n\n")
    f.write("@router.post(\"/api/admin/seed\")\n")
    f.write("async def seed_fixtures(\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    authz.require_organizer()\n")
    f.write("    counts = seed_database(db)\n")
    f.write("    credentials = get_checker_credentials(db)\n")
    f.write("    return {\n")
    f.write("        \"message\": \"Database seeded successfully\",\n")
    f.write("        \"counts\": counts,\n")
    f.write("        \"checker_credentials\": credentials\n")
    f.write("    }\n\n")
    f.write("@router.get(\"/api/admin/checker-credentials\")\n")
    f.write("async def get_checker_creds(\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    authz.require_organizer()\n")
    f.write("    credentials = get_checker_credentials(db)\n")
    f.write("    return credentials\n\n")
    f.write("from sqlalchemy import select, func\n")
    f.write("from app.models import Team, TeamMember, Track, Rubric, Criterion, JudgeAssignment, Review, Score, ReviewBatch\n")
    f.write("\n")
    f.write("print(\"Routes file complete\")\n")
print("Done part 3")
