with open("app/api/routes.py", "a", encoding="utf-8") as f:
    f.write("\n")
    f.write("@router.post(\"/api/auth/login\", response_model=LoginResponse)\n")
    f.write("async def login(\n")
    f.write("    request: LoginRequest,\n")
    f.write("    response: Response,\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    auth_service = AuthService(db)\n")
    f.write("    user = auth_service.authenticate(request.username, request.password)\n")
    f.write("    if not user:\n")
    f.write("        raise HTTPException(\n")
    f.write("            status_code=status.HTTP_401_UNAUTHORIZED,\n")
    f.write("            detail=\"Invalid credentials\"\n")
    f.write("        )\n")
    f.write("    if not user.is_active:\n")
    f.write("        raise HTTPException(\n")
    f.write("            status_code=status.HTTP_403_FORBIDDEN,\n")
    f.write("            detail=\"Account disabled\"\n")
    f.write("        )\n")
    f.write("    token = auth_service.create_session(user)\n")
    f.write("    response.set_cookie(\n")
    f.write("        key=\"session\",\n")
    f.write("        value=token,\n")
    f.write("        httponly=settings.session_cookie_httponly,\n")
    f.write("        secure=settings.session_cookie_secure,\n")
    f.write("        samesite=settings.session_cookie_samesite,\n")
    f.write("        max_age=settings.access_token_expire_minutes * 60\n")
    f.write("    )\n")
    f.write("    return LoginResponse(\n")
    f.write("        access_token=token,\n")
    f.write("        user=UserResponse.from_orm(user)\n")
    f.write("    )\n\n")
    f.write("@router.post(\"/api/auth/logout\")\n")
    f.write("async def logout(response: Response):\n")
    f.write("    response.delete_cookie(key=\"session\")\n")
    f.write("    return {\"message\": \"Logged out\"}\n\n")
    f.write("@router.get(\"/api/auth/me\", response_model=UserResponse)\n")
    f.write("async def get_current_user_info(current_user: User = Depends(get_current_user_required)):\n")
    f.write("    return UserResponse.from_orm(current_user)\n\n")
    f.write("@router.post(\"/api/events\", response_model=EventResponse)\n")
    f.write("async def create_event(\n")
    f.write("    event_data: EventCreate,\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    authz.require_organizer()\n")
    f.write("    event = Event(\n")
    f.write("        title=event_data.title,\n")
    f.write("        description=event_data.description,\n")
    f.write("        max_team_size=event_data.max_team_size,\n")
    f.write("        allow_late_submissions=event_data.allow_late_submissions,\n")
    f.write("        registration_open=event_data.registration_open,\n")
    f.write("        registration_close=event_data.registration_close,\n")
    f.write("        submissions_open=event_data.submissions_open,\n")
    f.write("        submissions_close=event_data.submissions_close,\n")
    f.write("        judging_open=event_data.judging_open,\n")
    f.write("        judging_close=event_data.judging_close,\n")
    f.write("        results_release=event_data.results_release,\n")
    f.write("    )\n")
    f.write("    db.add(event)\n")
    f.write("    db.flush()\n")
    f.write("    auth_service = AuthService(db)\n")
    f.write("    auth_service.assign_role(current_user.id, event.id, Role.ORGANIZER)\n")
    f.write("    db.commit()\n")
    f.write("    return EventResponse.from_orm(event)\n\n")
    f.write("@router.get(\"/api/events\", response_model=List[EventResponse])\n")
    f.write("async def list_events(\n")
    f.write("    db: Session = Depends(get_db),\n")
    f.write("    current_user: Optional[User] = Depends(get_current_user)\n")
    f.write("):\n")
    f.write("    events = db.execute(select(Event)).scalars().all()\n")
    f.write("    return [EventResponse.from_orm(e) for e in events]\n\n")
    f.write("@router.get(\"/api/events/{event_id}\", response_model=EventWithDetails)\n")
    f.write("async def get_event(\n")
    f.write("    event_id: int,\n")
    f.write("    db: Session = Depends(get_db),\n")
    f.write("    current_user: Optional[User] = Depends(get_current_user)\n")
    f.write("):\n")
    f.write("    event = db.get(Event, event_id)\n")
    f.write("    if not event:\n")
    f.write("        raise HTTPException(status_code=404, detail=\"Event not found\")\n")
    f.write("    tracks = db.execute(select(Track).where(Track.event_id == event_id)).scalars().all()\n")
    f.write("    rubrics = db.execute(select(Rubric).where(Rubric.event_id == event_id)).scalars().all()\n")
    f.write("    teams_count = db.execute(\n")
    f.write("        select(func.count(Team.id)).where(Team.event_id == event_id)\n")
    f.write("    ).scalar() or 0\n")
    f.write("    projects_count = db.execute(\n")
    f.write("        select(func.count(Project.id)).where(Project.event_id == event_id)\n")
    f.write("    ).scalar() or 0\n")
    f.write("    judges_count = db.execute(\n")
    f.write("        select(func.count(RoleMembership.id))\n")
    f.write("        .where(RoleMembership.event_id == event_id, RoleMembership.role == Role.JUDGE)\n")
    f.write("    ).scalar() or 0\n")
    f.write("    participants_count = db.execute(\n")
    f.write("        select(func.count(RoleMembership.id))\n")
    f.write("        .where(RoleMembership.event_id == event_id, RoleMembership.role == Role.PARTICIPANT)\n")
    f.write("    ).scalar() or 0\n")
    f.write("    response = EventWithDetails.from_orm(event)\n")
    f.write("    response.tracks = [TrackResponse.from_orm(t) for t in tracks]\n")
    f.write("    response.rubrics = []\n")
    f.write("    for r in rubrics:\n")
    f.write("        rubric_resp = RubricResponse.from_orm(r)\n")
    f.write("        criteria = db.execute(select(Criterion).where(Criterion.rubric_id == r.id)).scalars().all()\n")
    f.write("        rubric_resp.criteria = [CriterionResponse.from_orm(c) for c in criteria]\n")
    f.write("        response.rubrics.append(rubric_resp)\n")
    f.write("    response.teams_count = teams_count\n")
    f.write("    response.projects_count = projects_count\n")
    f.write("    response.judges_count = judges_count\n")
    f.write("    response.participants_count = participants_count\n")
    f.write("    return response\n\n")
    f.write("@router.patch(\"/api/events/{event_id}\", response_model=EventResponse)\n")
    f.write("async def update_event(\n")
    f.write("    event_id: int,\n")
    f.write("    event_data: EventUpdate,\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    authz.require_organizer(event_id)\n")
    f.write("    event = db.get(Event, event_id)\n")
    f.write("    if not event:\n")
    f.write("        raise HTTPException(status_code=404, detail=\"Event not found\")\n")
    f.write("    update_data = event_data.model_dump(exclude_unset=True)\n")
    f.write("    for field, value in update_data.items():\n")
    f.write("        setattr(event, field, value)\n")
    f.write("    db.commit()\n")
    f.write("    return EventResponse.from_orm(event)\n\n")
    f.write("@router.post(\"/api/events/{event_id}/teams\", response_model=TeamResponse)\n")
    f.write("async def create_team(\n")
    f.write("    event_id: int,\n")
    f.write("    team_data: TeamCreate,\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    authz.require_participant(event_id)\n")
    f.write("    event = db.get(Event, event_id)\n")
    f.write("    if not event:\n")
    f.write("        raise HTTPException(status_code=404, detail=\"Event not found\")\n")
    f.write("    if event.status not in [EventStatus.REGISTRATION, EventStatus.SUBMISSIONS]:\n")
    f.write("        raise HTTPException(status_code=403, detail=\"Team creation not allowed in current event state\")\n")
    f.write("    team = Team(event_id=event_id, name=team_data.name, description=team_data.description)\n")
    f.write("    db.add(team)\n")
    f.write("    db.flush()\n")
    f.write("    member = TeamMember(team_id=team.id, user_id=current_user.id, is_leader=True)\n")
    f.write("    db.add(member)\n")
    f.write("    db.commit()\n")
    f.write("    return TeamResponse.from_orm(team)\n\n")
    f.write("@router.get(\"/api/events/{event_id}/teams\", response_model=List[TeamResponse])\n")
    f.write("async def list_teams(\n")
    f.write("    event_id: int,\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    teams = db.execute(select(Team).where(Team.event_id == event_id)).scalars().all()\n")
    f.write("    return [TeamResponse.from_orm(t) for t in teams]\n\n")
    f.write("@router.get(\"/api/events/{event_id}/teams/{team_id}\", response_model=TeamResponse)\n")
    f.write("async def get_team(\n")
    f.write("    event_id: int,\n")
    f.write("    team_id: int,\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    team = db.get(Team, team_id)\n")
    f.write("    if not team or team.event_id != event_id:\n")
    f.write("        raise HTTPException(status_code=404, detail=\"Team not found\")\n")
    f.write("    return TeamResponse.from_orm(team)\n\n")
    f.write("@router.post(\"/api/events/{event_id}/teams/{team_id}/join\", response_model=TeamResponse)\n")
    f.write("async def join_team(\n")
    f.write("    event_id: int,\n")
    f.write("    team_id: int,\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    authz.require_participant(event_id)\n")
    f.write("    team = db.get(Team, team_id)\n")
    f.write("    if not team or team.event_id != event_id:\n")
    f.write("        raise HTTPException(status_code=404, detail=\"Team not found\")\n")
    f.write("    existing = db.execute(\n")
    f.write("        select(TeamMember)\n")
    f.write("        .join(Team, TeamMember.team_id == Team.id)\n")
    f.write("        .where(Team.event_id == event_id, TeamMember.user_id == current_user.id)\n")
    f.write("    ).scalar_one_or_none()\n")
    f.write("    if existing:\n")
    f.write("        raise HTTPException(status_code=400, detail=\"Already a member of a team in this event\")\n")
    f.write("    event = db.get(Event, event_id)\n")
    f.write("    member_count = db.execute(\n")
    f.write("        select(func.count(TeamMember.id)).where(TeamMember.team_id == team_id)\n")
    f.write("    ).scalar() or 0\n")
    f.write("    if member_count >= event.max_team_size:\n")
    f.write("        raise HTTPException(status_code=400, detail=\"Team is full\")\n")
    f.write("    member = TeamMember(team_id=team_id, user_id=current_user.id, is_leader=False)\n")
    f.write("    db.add(member)\n")
    f.write("    db.commit()\n")
    f.write("    return TeamResponse.from_orm(team)\n\n")
    f.write("@router.post(\"/api/events/{event_id}/projects\", response_model=ProjectResponse)\n")
    f.write("async def create_project(\n")
    f.write("    event_id: int,\n")
    f.write("    project_data: ProjectCreate,\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    team_member = db.execute(\n")
    f.write("        select(TeamMember)\n")
    f.write("        .join(Team, TeamMember.team_id == Team.id)\n")
    f.write("        .where(Team.event_id == event_id, TeamMember.user_id == current_user.id)\n")
    f.write("    ).scalar_one_or_none()\n")
    f.write("    if not team_member:\n")
    f.write("        raise HTTPException(status_code=403, detail=\"Must be a team member to create a project\")\n")
    f.write("    team_id = team_member.team_id\n")
    f.write("    event = db.get(Event, event_id)\n")
    f.write("    if not event:\n")
    f.write("        raise HTTPException(status_code=404, detail=\"Event not found\")\n")
    f.write("    if event.status != EventStatus.SUBMISSIONS:\n")
    f.write("        raise HTTPException(status_code=403, detail=\"Submissions not open\")\n")
    f.write("    if event.submissions_close and datetime.now(timezone.utc) > event.submissions_close:\n")
    f.write("        if not event.allow_late_submissions:\n")
    f.write("            raise HTTPException(status_code=403, detail=\"Submission deadline has passed\")\n")
    f.write("    project = Project(\n")
    f.write("        event_id=event_id,\n")
    f.write("        team_id=team_id,\n")
    f.write("        track_id=project_data.track_id,\n")
    f.write("        title=project_data.title,\n")
    f.write("        description=project_data.description,\n")
    f.write("        repo_url=str(project_data.repo_url) if project_data.repo_url else None,\n")
    f.write("        demo_url=str(project_data.demo_url) if project_data.demo_url else None,\n")
    f.write("        video_url=str(project_data.video_url) if project_data.video_url else None,\n")
    f.write("        status=ProjectStatus.DRAFT\n")
    f.write("    )\n")
    f.write("    db.add(project)\n")
    f.write("    db.commit()\n")
    f.write("    return ProjectResponse.from_orm(project)\n\n")
    f.write("@router.patch(\"/api/events/{event_id}/projects/{project_id}\", response_model=ProjectResponse)\n")
    f.write("async def update_project(\n")
    f.write("    event_id: int,\n")
    f.write("    project_id: int,\n")
    f.write("    project_data: ProjectUpdate,\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    project = db.get(Project, project_id)\n")
    f.write("    if not project or project.event_id != event_id:\n")
    f.write("        raise HTTPException(status_code=404, detail=\"Project not found\")\n")
    f.write("    team_member = db.execute(\n")
    f.write("        select(TeamMember).where(\n")
    f.write("            TeamMember.team_id == project.team_id,\n")
    f.write("            TeamMember.user_id == current_user.id\n")
    f.write("        )\n")
    f.write("    ).scalar_one_or_none()\n")
    f.write("    if not team_member:\n")
    f.write("        raise HTTPException(status_code=403, detail=\"Not a member of this project's team\")\n")
    f.write("    event = db.get(Event, event_id)\n")
    f.write("    if project.status == ProjectStatus.SUBMITTED and event.status != EventStatus.SUBMISSIONS:\n")
    f.write("        raise HTTPException(status_code=403, detail=\"Cannot modify submitted project\")\n")
    f.write("    update_data = project_data.model_dump(exclude_unset=True)\n")
    f.write("    for field, value in update_data.items():\n")
    f.write("        if field in [\"repo_url\", \"demo_url\", \"video_url\"] and value:\n")
    f.write("            value = str(value)\n")
    f.write("        setattr(project, field, value)\n")
    f.write("    db.commit()\n")
    f.write("    return ProjectResponse.from_orm(project)\n\n")
    f.write("@router.post(\"/api/events/{event_id}/projects/{project_id}/submit\", response_model=ProjectResponse)\n")
    f.write("async def submit_project(\n")
    f.write("    event_id: int,\n")
    f.write("    project_id: int,\n")
    f.write("    current_user: User = Depends(get_current_user_required),\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    authz = Authz(db, current_user)\n")
    f.write("    authz.require_participant(event_id)\n")
    f.write("    project = db.get(Project, project_id)\n")
    f.write("    if not project or project.event_id != event_id:\n")
    f.write("        raise HTTPException(status_code=404, detail=\"Project not found\")\n")
    f.write("    team_member = db.execute(\n")
    f.write("        select(TeamMember).where(\n")
    f.write("            TeamMember.team_id == project.team_id,\n")
    f.write("            TeamMember.user_id == current_user.id\n")
    f.write("        )\n")
    f.write("    ).scalar_one_or_none()\n")
    f.write("    if not team_member:\n")
    f.write("        raise HTTPException(status_code=403, detail=\"Not a member of this project's team\")\n")
    f.write("    event = db.get(Event, event_id)\n")
    f.write("    if not event:\n")
    f.write("        raise HTTPException(status_code=404, detail=\"Event not found\")\n")
    f.write("    if event.submissions_close and datetime.now(timezone.utc) > event.submissions_close:\n")
    f.write("        if not event.allow_late_submissions:\n")
    f.write("            project.status = ProjectStatus.LATE_REFUSED\n")
    f.write("            db.commit()\n")
    f.write("            raise HTTPException(status_code=403, detail=\"Submission deadline has passed\")\n")
    f.write("    if project.status == ProjectStatus.SUBMITTED:\n")
    f.write("        raise HTTPException(status_code=400, detail=\"Project already submitted\")\n")
    f.write("    project.status = ProjectStatus.SUBMITTED\n")
    f.write("    project.submitted_at = datetime.now(timezone.utc)\n")
    f.write("    db.commit()\n")
    f.write("    return ProjectResponse.from_orm(project)\n\n")
    f.write("@router.get(\"/api/projects\", response_model=List[ProjectWithDetails])\n")
    f.write("async def public_gallery(\n")
    f.write("    event_id: Optional[int] = None,\n")
    f.write("    track_id: Optional[int] = None,\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    query = select(Project).where(Project.status == ProjectStatus.SUBMITTED)\n")
    f.write("    if event_id:\n")
    f.write("        query = query.where(Project.event_id == event_id)\n")
    f.write("    if track_id:\n")
    f.write("        query = query.where(Project.track_id == track_id)\n")
    f.write("    projects = db.execute(query).scalars().all()\n")
    f.write("    results = []\n")
    f.write("    for project in projects:\n")
    f.write("        team = db.get(Team, project.team_id)\n")
    f.write("        track = db.get(Track, project.track_id) if project.track_id else None\n")
    f.write("        proj_detail = ProjectWithDetails.from_orm(project)\n")
    f.write("        proj_detail.team_name = team.name if team else None\n")
    f.write("        proj_detail.track_name = track.name if track else None\n")
    f.write("        proj_detail.vote_count = 0\n")
    f.write("        results.append(proj_detail)\n")
    f.write("    return results\n\n")
    f.write("@router.get(\"/fixtures/projects\", response_model=List[ProjectWithDetails])\n")
    f.write("async def fixture_projects(\n")
    f.write("    event_id: Optional[int] = None,\n")
    f.write("    db: Session = Depends(get_db)\n")
    f.write("):\n")
    f.write("    query = select(Project).where(Project.is_fixture == True)\n")
    f.write("    if event_id:\n")
    f.write("        query = query.where(Project.event_id == event_id)\n")
    f.write("    projects = db.execute(query).scalars().all()\n")
    f.write("    results = []\n")
    f.write("    for project in projects:\n")
    f.write("        team = db.get(Team, project.team_id)\n")
    f.write("        track = db.get(Track, project.track_id) if project.track_id else None\n")
    f.write("        proj_detail = ProjectWithDetails.from_orm(project)\n")
    f.write("        proj_detail.team_name = team.name if team else None\n")
    f.write("        proj_detail.track_name = track.name if track else None\n")
    f.write("        results.append(proj_detail)\n")
    f.write("    return results\n\n")
    f.write("@router.post(\"/projects/new\")\n")
    f.write("async def submit_project_checker(\n")
    f.write("    request: Request,\n")
    f.write("    db: Session = Depends(get_db),\n")
    f.write("    session: Optional[str] = Cookie(None, alias=\"session\")\n")
    f.write("):\n")
    f.write("    payload = verify_session_token(session) if session else None\n")
    f.write("    if not payload:\n")
    f.write("        raise HTTPException(status_code=401, detail=\"Authentication required\")\n")
    f.write("    user_id = int(payload.get(\"sub\", 0))\n")
    f.write("    auth_service = AuthService(db)\n")
    f.write("    user = auth_service.get_user(user_id)\n")
    f.write("    if not user or not auth_service.has_role(user_id, 1, Role.PARTICIPANT):\n")
    f.write("        raise HTTPException(status_code=403, detail=\"Participant role required\")\n")
    f.write("    event = db.execute(select(Event).where(Event.is_fixture == True)).scalar_one_or_none()\n")
    f.write("    if event and event.submissions_close and datetime.now(timezone.utc) > event.submissions_close:\n")
    f.write("        if not event.allow_late_submissions:\n")
    f.write("            raise HTTPException(status_code=403, detail=\"Submission deadline has passed\")\n")
    f.write("    body = await request.json()\n")
    f.write("    title = body.get(\"title\", \"Untitled\")\n")
    f.write("    summary = body.get(\"summary\", \"\")\n")
    f.write("    project = Project(\n")
    f.write("        event_id=1,\n")
    f.write("        team_id=1,\n")
    f.write("        title=title,\n")
    f.write("        description=summary,\n")
    f.write("        status=ProjectStatus.SUBMITTED,\n")
    f.write("        submitted_at=datetime.now(timezone.utc)\n")
    f.write("    )\n")
    f.write("    db.add(project)\n")
    f.write("    db.commit()\n")
    f.write("    return {\"id\": project.id, \"title\": project.title, \"status\": project.status.value}\n\n")
print("Done part 2")
